### PR TITLE
Add aiohttp regression tests to CI

### PR DESCRIPTION
**Pull request by Dreamsorcerer**

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
@ShogunPanda I doubt this'll work first time. If you can maybe lift the workflow restrictions for new contributors temporarily, then I can try and iterate on it till it works.

**Comment by Dreamsorcerer** [comment]
I'm testing within the fork. It almost works, but fails to import the compiled parser for some reason. Will get back when it's fixed.

**Comment by ShogunPanda** [comment]
@Dreamsorcerer This looks go to me. Once aiohttp is all green with llhttp I'll merge this.

**Comment by benz0li** [comment]
> Once aiohttp is all green with llhttp I'll merge this.

@ShogunPanda The issue is on `llhttp`'s side. If you do not agree, express your opinion accordingly.

**Comment by ShogunPanda** [comment]
@benz0li @Dreamsorcerer I get a failure on llhttp CI. Can you please verify it?

**Comment by benz0li** [comment]
> @benz0li @Dreamsorcerer I get a failure on llhttp CI. Can you please verify it?

If you are talking about https://github.com/nodejs/llhttp/actions/runs/6225384656/job/16918217042?pr=250:

> The 100_continue test failures are https://github.com/nodejs/llhttp/issues/249.

This needs to be fixed on `llhttp`'s side.

**Comment by benz0li** [comment]
@Dreamsorcerer @ShogunPanda Apparently you both disagree about which side is causing the problem.

Please clarify this as soon as possible. Thank you.

**Comment by Dreamsorcerer** [comment]
Yes, as mentioned above, the 100_continue failures:
https://github.com/nodejs/llhttp/actions/runs/6225384656/job/16918217042?pr=250#step:9:701

They are caused by #249, so if you merge this in now, you can use the CI to verify any fixes to that issue (i.e. you'll see those 2 failures disappear in the PR that fixes it)..

**Comment by benz0li** [comment]
@indutny As the initiator of `llhttp`, I would greatly appreciate your objective view on this.

**Comment by ShogunPanda** [comment]
Released v9.1.3.

**Comment by Dreamsorcerer** [comment]
@ShogunPanda Thanks a lot. That's merged now, so if you rerun the last test run on master, then it should go green now:
https://github.com/nodejs/llhttp/actions/runs/6394836947/job/17357138399

**Pull request merged**
