### PR TITLE
Fix zero length chunked response regression

### PR DESCRIPTION
**Pull request by bdraco**
This test fails on 9.1.3 but passes on 8.1.1

related issues https://github.com/aio-libs/aiohttp/pull/7697 https://github.com/home-assistant/core/issues/101893 https://github.com/home-assistant/core/pull/101913

### CODE REVIEW

**Comment by cdce8p** [comment]
Narrowed it down to this line
https://github.com/nodejs/llhttp/blob/9ab2afc85b2880d96a94d38afaee301c6a314049/src/native/http.c#L65

Removing it here, resolves the issue.

/CC @ShogunPanda Would you mind taking a look?

**Comment by bdraco** [comment]
Looks like that fix causes other tests to fail https://github.com/bdraco/llhttp/actions/runs/6566967226/job/17838778913?pr=1

Digging...

**Comment by bdraco** [comment]
Test existing test was missing the ending 0 

https://github.com/bdraco/llhttp/actions/runs/6567209475?pr=1

**Review by ShogunPanda — APPROVED** [review]
LGTM!

**Comment by tatsuhiro-t** [comment]
RFC 9112 dictates that 304 response does not have message body.

> Any response to a HEAD request and any response with a 1xx (Informational), 204 (No Content), or 304 (Not Modified) status code is always terminated by the first empty line after the header fields, regardless of the header fields present in the message, and thus cannot contain a message body or trailer section.

and

> Transfer-Encoding MAY be sent in a response to a HEAD request or in a 304 (Not Modified) response ([Section 15.4.5](https://www.rfc-editor.org/rfc/rfc9110#section-15.4.5) of [[HTTP](https://datatracker.ietf.org/doc/html/rfc9110)]) to a GET request, neither of which includes a message body, to indicate that the origin server would have applied a transfer coding to the message body if the request had been an unconditional GET. This indication is not required, however, because any recipient on the response chain (including the origin server) can remove transfer codings when they are not needed.

It is allowed to send transfer-encoding header field in 304 response, but it must be ignored because the message body must be empty.

I think this PR should be reverted.

**Comment by bdraco** [comment]
> RFC 9112 dictates that 304 response does not have message body.
> 
> > Any response to a HEAD request and any response with a 1xx (Informational), 204 (No Content), or 304 (Not Modified) status code is always terminated by the first empty line after the header fields, regardless of the header fields present in the message, and thus cannot contain a message body or trailer section.
> 
> and
> 
> > Transfer-Encoding MAY be sent in a response to a HEAD request or in a 304 (Not Modified) response ([Section 15.4.5](https://www.rfc-editor.org/rfc/rfc9110#section-15.4.5) of [[HTTP](https://datatracker.ietf.org/doc/html/rfc9110)]) to a GET request, neither of which includes a message body, to indicate that the origin server would have applied a transfer coding to the message body if the request had been an unconditional GET. This indication is not required, however, because any recipient on the response chain (including the origin server) can remove transfer codings when they are not needed.
> 
> It is allowed to send transfer-encoding header field in 304 response, but it must be ignored because the message body must be empty.
> 
> I think this PR should be reverted.

Unfortunately this means this is a breaking change between 8.x and 9.x, but I agree with how you read the rfc.

**Comment by ShogunPanda** [comment]
Reverted in #262.
@tatsuhiro-t Thanks for flagging this, it completely slipped my radar.

**Pull request merged**
