### PR TITLE
Speedup tests execution

### PR DESCRIPTION
**Pull request by fanatid**
On my laptop with 8 cpus:

Without: `1m16.364s`
With: `0m22.755s`

### CODE REVIEW

**Comment by indutny** [comment]
Could you elaborate on how this works?

**Comment by fanatid** [comment]
In `runSingleTest` instead define execution code in mocha function `it` I send it to queue created by [fanatid/make-concurrent](https://github.com/fanatid/make-concurrent). Result of this push opearion is Promise, so in `it` I just return it.
Function in queue, check input and return promise, but before return I also add `.catch`, because otherwise on error there will be additional `unhandledRejection` warnings.
Queue itself hold all functions for execution (FIFO), but execute not more than value in option `concurrency`.
So, in reality we run check in parallel (FIFO), but for mocha it looks like not parallel process (like queue with size 1).

I still was not able loading all CPUs (800% in my case). I think most issue in creating process, with this patch there will be 525 processes spawns right now. Without with defined in `maxParallel` (test/fixtures/index.ts) equal to number of cpus there was much more processes, so things was slower.

--
sorry, not sure that my explanation looks obvious =\

**Comment by fanatid** [comment]
Probably better explanation (abstract):
- We have 2 queues: execution queue and mocha queue. Both queues FIFO, both have same order of tests.
- Execution queue contains functions which are our tests.
- Mocha queues contains promises which are results of functions from execution queue (will be fulfilled/rejected in future, when function contains tests will be finished).
- Execution queue have concurrency option which allow execute few functions at one time in defined order.
- Mocha queue do not have concurrency option and wait every promise (fulfilled/rejected) in defined order.

Why it's faster?
Because instead creating few processes with chunks for checking we create one process. (process creation is not cheap operation, right?) As mentioned above with this PR 525 processed created, without with 8 CPU: 525*8=4200.
While we create one process per test we run few tests at one time. So each process do bigger job.

**Comment by indutny** [comment]
How does a test failure look like with this change? Does it still get reported under particular name `it()` has?

**Comment by fanatid** [comment]
It should be, because Promise will contain error which will be handled by `it()`.

**Comment by indutny** [comment]
Nice!

I'd like to play with it a bit before landing. Could you rebase the PR, please?

**Comment by fanatid** [comment]
Done :+1:

**Comment by fanatid** [comment]
Regarding output to stderr from spawned process... if this PR will me landed then things will be mixed. But this new issue should be fixed with https://github.com/fanatid/llparse-test-fixture/commit/f15ad7b896f8b0c7583bce70443287400368574a (this from branch with win32 support https://github.com/fanatid/llparse-test-fixture/tree/win-support currently working on testing llhttp on win32).

**Comment by indutny** [comment]
Here's what I'm getting in console when modifying a test to make it fail:

```
(node:53533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:53533) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Executable: http-loose-request
Scan value: 1 at line: 1
  output  : off=0 message begin
off=4 len=4 span[url]="/url"
off=19 len=10 span[header_field]="Connection"
off=31 len=10 span[header_value]="keep-alive"
off=45 headers complete method=4 v=1/1 flags=1 content_length=0
off=45 message complete

    at /Users/findutnyy/Code/indutny/llhttp/node_modules/llparse-test-fixture/src/result.ts:152:16
    at Array.forEach (<anonymous>)
    at FixtureResult.checkScan (/Users/findutnyy/Code/indutny/llhttp/node_modules/llparse-test-fixture/src/result.ts:148:11)
    at /Users/findutnyy/Code/indutny/llhttp/node_modules/llparse-test-fixture/src/result.ts:52:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at FixtureResult.check (/Users/findutnyy/Code/indutny/llhttp/node_modules/llparse-test-fixture/src/result.ts:49:5)
```

**Comment by fanatid** [comment]
Hmmm, I see it too! But I remember that I test such cases :thinking: 
Will fix shortly, sorry =(

**Comment by fanatid** [comment]
Fixed. Please, try again.

**Comment by indutny** [comment]
Thanks, looks better now!

I now see how it works. This PR starts the jobs outside of the mocha tests and just lets mocha await them. They complete quite fast indeed, but the price is that one can no longer grep specific mocha tests without running all of them. Is it right?

**Comment by fanatid** [comment]
Ah, I completely forgot about `it.only` do you mean this? (Usually I use tape and there `only` not exists)

While worked on #38 I added code like `if (!name.includes('...')) return` to `runTest` before `describe` and run only specified test.

**Comment by fanatid** [comment]
How you run some specified test now?

**Comment by indutny** [comment]
`npm run mocha -- --grep "test-name"`

**Comment by indutny** [comment]
No problem at all!

I think one possible solution could be to move away from mocha. Given that the tests live in markdown there is no need to have a specific test runner to execute them.

**Comment by fanatid** [comment]
In [child_process](https://nodejs.org/api/child_process.html) docs:
> On Unix-like operating systems, the child_process.spawn() method performs memory operations synchronously before decoupling the event loop from the child. Applications with a large memory footprint may find frequent child_process.spawn() calls to be a bottleneck. For more information, see V8 issue 7381.

Is this can be relevant with performance here? (because tests spawn a lot of processes)

**Comment by indutny** [comment]
🤷‍♂

Could be...

**Comment by jehy** [comment]
Jest plays nice with multithreading, I even use it as a runner for my mocha tests, you can try it.

**Comment by indutny** [comment]
I believe I landed this?

**Pull request closed without merging**
