### PR TITLE
ci: change travis to gh actions + Windows support

### PR DESCRIPTION
**Pull request by fanatid**
Why GitHub Actions? Because support 3 platform at one place.

Are you interesting in running tests on Windows? (will need extra efforts in `llparse-test-fixtures` for fixing `sys/time.h` header)

CI files can be applied to other llhttp repos.

CI status: https://github.com/fanatid/llhttp/actions

### CODE REVIEW

**Comment by indutny** [comment]
Wow! This is super nice!

**Comment by indutny** [comment]
Should it remove travis badge from readme then?

**Comment by fanatid** [comment]
Oh, forgot about badge. Do you want GitHub actions badge? I'm not sure about markdown code for it, but I can try to find.

**Comment by indutny** [comment]
It is not necessary, but would be great to have if it is not too hard to get it!

**Comment by fanatid** [comment]
OK, bad parts:
- If PR created from branch in original repo, then CI trigger twice. Details: https://github.com/fanatid/llhttp/pull/2#issuecomment-572216527 (but I think this can be ignored)
- Badge possible only per workflow. Previously I created 3 (lint, test, build), now moved to one. But found that it display last triggered CI. Push/PR for any branch. This means, that it's not possible easily use it (possible if we copy-paste workflow for push to master branch only).
- A lot of things copy-pasted in workflow. 1) clang installation twice 2) repo clone / cache / deps install repeated 3 times. And it's not possible share all this between jobs =(

Despite the points above I still think that GitHub actions better than travis now, because allow test Linux/macOS/Windows.
Finally, should we build `libllhttp.a` on windows? (i.e. patch `llparse-test-fixtures) or just drop windows for now?

**Comment by fanatid** [comment]
It was hard! Windows in VirtualBox freeze my OS, while tried to fix I accidentally removed kernel modules and was need reinstall OS! :joy:
Require https://github.com/nodejs/llparse-test-fixture/pull/4 (I'll update `package.json` in this PR when required PR will be landed).
CI on GitHub: https://github.com/fanatid/llhttp/commit/1af6377021929605e3353b08bbfcab1a03938e8e/checks?check_suite_id=394830460

**Comment by indutny** [comment]
> Finally, should we build libllhttp.a on windows? (i.e. patch `llparse-test-fixtures`) or just drop windows for now?

I don't think that we should unless someone will request it.

Should we wait for the test-fixture PR to be landed first before landing this?

**Comment by fanatid** [comment]
`libhttp.a` on windows right now is OK (sorry that did not update message), see https://github.com/fanatid/llhttp/commit/1af6377021929605e3353b08bbfcab1a03938e8e/checks?check_suite_id=394830460

> Should we wait for the test-fixture PR to be landed first before landing this?

Yes, better wait test-fixture PR before land this. I also will need update test-fixture version in this PR before landing.

**Comment by fanatid** [comment]
Rebased, will update llparse-test-fixture to 4.0.0 in another PR.
CI: https://github.com/fanatid/llhttp/commit/a8d456d77b73ff4f7f5d8ce6f1c4ddc27d3bc7ec/checks?check_suite_id=403460246

**Comment by cclauss** [comment]
> Why GitHub Actions? Because support 3 platform at one place.
Travis CI, CircleCI, Azure, Jenkins also support all 3 at once with more OS versions possible.  However GitHub Actions is built-it and is modern and easy to work with so I am highly supportive of this PR.

**Comment by indutny** [comment]
@fanatid is it ready to land? (Sorry for delay)

**Comment by fanatid** [comment]
Yes, I think it's ready to land.

**Comment by indutny** [comment]
Thanks!

**Pull request merged**
