### PR TITLE
src: refactor code

### PR DESCRIPTION
**Pull request by aymen94**
make code robust, maintainable and easy to understand

### CODE REVIEW

**Comment by aymen94** [comment]
@indutny @cjihrig

**Comment by cjihrig** [comment]
Most of the changes here appear to be purely stylistic.

**Comment by aymen94** [comment]
@cjihrig yes, is for code Maintenance

**Comment by indutny** [comment]
@aymen94 thank you for this contribution. After a quick review, I have to agree with @cjihrig . There is a term called "code churn", and this Pull Request does exactly this. I'm afraid that the benefits of this change do not outweigh amount of "code churn". Sorry!

**Pull request closed without merging**
