### PR TITLE
feat: Get rid of enums.

### PR DESCRIPTION
**Pull request by ShogunPanda**
@Uzlopak I had to remove `-r` in the test run script to avoid starting a REPL locally. Was yours a leftover or am I missing someting?

### CODE REVIEW

**Comment by Uzlopak** [comment]
@ShogunPanda 
Oh! I thought this is how it fixes the windows test. But it works now. So everything went well. Nice.

I would not call the interface Enum. Maybe `TokenDict` or something like this.

**Comment by ShogunPanda** [comment]
Done, what about now?

**Comment by Uzlopak** [comment]
I dont know how strict you want your IntDict to actually be. 

This is when you want them to be more strict. [Typescript Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAChApgVwCYgKJmQWwFwwDeAsAFAwUwYBK1A8tQQIwDcZlMAagIIAyAkgBECAJjakAvjAC8RdpRr1GMJgBp5FHgOEwRZCWTIAzZGGBQAluBhGwACkQAnRwGEQqRASgBPAA6IQI3gkNExsHABtAGtEb0CYH394hBR0LFwAXQBKOXJKCAB3CyhgAAsYB2c3DxySPI4KYABDJBU8DQaKAHoumAA3JoAbC1RxTsaWxF12+vGe-qGRsfHm1oBmGfHKeYswAeHUDoNJIA)

Thats why I wrote, that you would basically duplicate the code, once as an interface and once for the the Object. 

But this is just fyi. If you like it more strict, than this is the way to go. Or maybe not. Your decision ;).

**Review by Uzlopak — APPROVED** [review]
LGTM 

:)

**Comment by ShogunPanda** [comment]
Since we use them internally (as llhttp it not published anymore on NPM) I don't it cares too much.
Eventually we can revisit in the future. Merging this.

**Pull request merged**
