### PR TITLE
Add HTTP statuses

### LINKED ISSUE #106: http_status
Hi,

we tried to move from http_parser to llhttp. Is it possible to provide a `http_status`, too?

### PR DESCRIPTION
**Pull request by ShogunPanda**
Fixes #106.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
This might need docs

**Comment by ShogunPanda** [comment]
@mcollina How would you add docs to this? There is no actual documentation at all here on how to use the API beside the WASM example.

**Comment by mcollina** [comment]
no worries!

**Pull request merged**
